name: code quality checks

on:
  pull_request:

jobs:
  pre-commit:
    name: run pre-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: julia-actions/setup-julia@v2
      with:
        version: 1
    - run: |
          julia --project=@runic -e '
            using Pkg
            Pkg.add("Runic")'
      env:
        PYTHON: ""
    - uses: actions/setup-python@v6
    - uses: pre-commit/action@v3.0.1
